version: '3.1'

networks:
  testnetwork:
    driver: bridge

services:

  ## сервис контейнер для эмуляции обращений к внешнему апи
  container-stub:
    container_name: container-stub
    build: .docker/stubs
    entrypoint: ["sh", "entrypoint.sh"]
    networks:
      - testnetwork
    ports:
      - "8888:80"

  ## сервис-контейнер для вашего кода. 
  ## При необходимости донастройте его по вашим потребностям
  container-testcase:
    container_name: container-testcase
    build: .docker/testcase
    entrypoint: ["sh", "/entrypoint.sh"]
    volumes:
      - ./src:/var/www/html:rw
    networks:
      - testnetwork
    ports:
      - "8008:80"

  ## база данных
  container-database:
    container_name: container-database
    image: postgres:latest
    environment:
      POSTGRES_DB: minishop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - testnetwork

volumes:
  postgres_data: