<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240913101307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE carts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE carts ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE carts ALTER delivery_service_id DROP NOT NULL');
        $this->addSql('ALTER TABLE carts ALTER payment_service_id DROP NOT NULL');
        $this->addSql('ALTER TABLE carts ALTER is_pay DROP DEFAULT');
        $this->addSql('ALTER TABLE carts ALTER total_payment_sum DROP NOT NULL');
        $this->addSql('ALTER TABLE delivery_services ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE delivery_services ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE delivery_services ALTER code TYPE VARCHAR(10)');
        $this->addSql('ALTER TABLE delivery_services ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE payment_services ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE payment_services ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE payment_services ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE products ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE products ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE products ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE products ALTER image DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE carts ALTER id SET DEFAULT carts_id_seq');
        $this->addSql('ALTER TABLE carts ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE carts ALTER delivery_service_id SET NOT NULL');
        $this->addSql('ALTER TABLE carts ALTER payment_service_id SET NOT NULL');
        $this->addSql('ALTER TABLE carts ALTER is_pay SET DEFAULT 0');
        $this->addSql('ALTER TABLE carts ALTER total_payment_sum SET NOT NULL');
        $this->addSql('ALTER TABLE delivery_services ALTER id SET DEFAULT delivery_services_id_seq');
        $this->addSql('ALTER TABLE delivery_services ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE delivery_services ALTER code TYPE CHAR(10)');
        $this->addSql('ALTER TABLE delivery_services ALTER name TYPE CHAR(255)');
        $this->addSql('ALTER TABLE products ALTER id SET DEFAULT products_id_seq');
        $this->addSql('ALTER TABLE products ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE products ALTER name TYPE CHAR(255)');
        $this->addSql('ALTER TABLE products ALTER image SET NOT NULL');
        $this->addSql('ALTER TABLE payment_services ALTER id SET DEFAULT payment_services_id_seq');
        $this->addSql('ALTER TABLE payment_services ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE payment_services ALTER name TYPE CHAR(255)');
    }
}
